MashadLeatherEcommerce/Models/Entities/CarreerIntroduced.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Models
{
    public class CarreerIntroduced : BaseEntity
    {
        [Display(Name = "نام و نام خانوادگی")]
        public string FullName { get; set; }
        [Display(Name = "نسبت")]
        public string Relationship { get; set; }
        [Display(Name = "شغل")]
        public string Job { get; set; }
        [Display(Name = "محل کار")]
        public string WorkPlace { get; set; }
        [Display(Name = "تلفن منزل")]
        public string HomePhone { get; set; }
        [Display(Name = "تلفن همراه")]
        public string CellNumber { get; set; }
        [Display(Name = "آدرس")]
        public string Address { get; set; }
        [Display(Name = "کارجو")]
        public Guid CarreerId { get; set; }
        public virtual Carreer Carreer { get; set; }
    }
}

MashadLeatherEcommerce/Controllers/CarreerIntroducedsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Models;

namespace MashadLeatherEcommerce.Controllers
{
    public class CarreerIntroducedsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: CarreerIntroduceds
        public ActionResult Index()
        {
            var carreerIntroduceds = db.CarreerIntroduceds.Include(c => c.Carreer).Where(c=>c.IsDeleted==false).OrderByDescending(c=>c.CreationDate);
            return View(carreerIntroduceds.ToList());
        }

        // GET: CarreerIntroduceds/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarreerIntroduced carreerIntroduced = db.CarreerIntroduceds.Find(id);
            if (carreerIntroduced == null)
            {
                return HttpNotFound();
            }
            return View(carreerIntroduced);
        }

        // GET: CarreerIntroduceds/Create
        public ActionResult Create()
        {
            ViewBag.CarreerId = new SelectList(db.Carreers.Where(c => c.IsDeleted == false), "Id", "FullName");
            return View();
        }

        // POST: CarreerIntroduceds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CarreerIntroduced carreerIntroduced)
        {
            if (ModelState.IsValid)
            {
				carreerIntroduced.IsDeleted=false;
				carreerIntroduced.CreationDate= DateTime.Now; 
					
                carreerIntroduced.Id = Guid.NewGuid();
                db.CarreerIntroduceds.Add(carreerIntroduced);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CarreerId = new SelectList(db.Carreers.Where(c => c.IsDeleted == false), "Id", "FullName", carreerIntroduced.CarreerId);
            return View(carreerIntroduced);
        }

        // GET: CarreerIntroduceds/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarreerIntroduced carreerIntroduced = db.CarreerIntroduceds.Find(id);
            if (carreerIntroduced == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarreerId = new SelectList(db.Carreers.Where(c => c.IsDeleted == false), "Id", "FullName", carreerIntroduced.CarreerId);
            return View(carreerIntroduced);
        }

        // POST: CarreerIntroduceds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CarreerIntroduced carreerIntroduced)
        {
            if (ModelState.IsValid)
            {
				carreerIntroduced.IsDeleted=false;
					carreerIntroduced.LastModifiedDate=DateTime.Now;
                db.Entry(carreerIntroduced).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarreerId = new SelectList(db.Carreers.Where(c => c.IsDeleted == false), "Id", "FullName", carreerIntroduced.CarreerId);
            return View(carreerIntroduced);
        }

        // GET: CarreerIntroduceds/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarreerIntroduced carreerIntroduced = db.CarreerIntroduceds.Find(id);
            if (carreerIntroduced == null)
            {
                return HttpNotFound();
            }
            return View(carreerIntroduced);
        }

        // POST: CarreerIntroduceds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            CarreerIntroduced carreerIntroduced = db.CarreerIntroduceds.Find(id);
			carreerIntroduced.IsDeleted=true;
			carreerIntroduced.DeletionDate=DateTime.Now;
 
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MashadLeatherEcommerce/Views/CarreerIntroduceds/Create.cshtml
@model Models.CarreerIntroduced

@{
    ViewBag.Title = "افزودن " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>افزودن @Html.DisplayNameFor(model => model)</h2>

@using (Html.BeginForm("Create", "CarreerIntroduceds",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        @Html.ValidationSummary(true)

        <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.FullName)

                @Html.ValidationMessageFor(model => model.FullName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Relationship, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Relationship)

                @Html.ValidationMessageFor(model => model.Relationship)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Job, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Job)

                @Html.ValidationMessageFor(model => model.Job)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkPlace, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.WorkPlace)

                @Html.ValidationMessageFor(model => model.WorkPlace)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.HomePhone)

                @Html.ValidationMessageFor(model => model.HomePhone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.CellNumber)

                @Html.ValidationMessageFor(model => model.CellNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Address)

                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarreerId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarreerId", String.Empty)
                @Html.ValidationMessageFor(model => model.CarreerId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)


                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)

                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionEn, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.DescriptionEn)

                @Html.ValidationMessageFor(model => model.DescriptionEn)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionAr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.DescriptionAr)

                @Html.ValidationMessageFor(model => model.DescriptionAr)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ایجاد" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
        </div>
</div>
}

MashadLeatherEcommerce/Views/CarreerIntroduceds/Delete.cshtml
@model Models.CarreerIntroduced

@{
    ViewBag.Title = "حذف " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>آیا از حذف این مورد اطمینان دارید؟</h3>
<div>    
    <hr />
    <div class="form-horizontal">        
    
         <div class="form-group">
            @Html.LabelFor(model => model.Carreer.FullName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Carreer.FullName)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.FullName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.FullName)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Relationship, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Relationship)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Job, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Job)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.WorkPlace, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.WorkPlace)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.HomePhone)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CellNumber, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CellNumber)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Address)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.IsActive)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.CreationDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedDate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.LastModifiedDate)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Description)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.DescriptionEn, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.DescriptionEn)
      </div></div>

         <div class="form-group">
            @Html.LabelFor(model => model.DescriptionAr, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.DescriptionAr)
      </div></div>

  </div>  

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

       <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تایید حذف" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    }
</div>

MashadLeatherEcommerce/Views/CarreerIntroduceds/Details.cshtml
@model Models.CarreerIntroduced

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CarreerIntroduced</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Carreer.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Carreer.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Relationship)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relationship)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkPlace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkPlace)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CellNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CellNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeletionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeletionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionEn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionEn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescriptionAr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescriptionAr)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MashadLeatherEcommerce/Views/CarreerIntroduceds/Edit.cshtml
@model Models.CarreerIntroduced

@{
    ViewBag.Title = "ویرایش " + Server.HtmlDecode(Html.DisplayNameFor(model => model).ToString());
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "CarreerIntroduceds",FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.FullName)
                @Html.ValidationMessageFor(model => model.FullName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Relationship, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Relationship)
                @Html.ValidationMessageFor(model => model.Relationship)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Job, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Job)
                @Html.ValidationMessageFor(model => model.Job)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkPlace, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.WorkPlace)
                @Html.ValidationMessageFor(model => model.WorkPlace)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.HomePhone)
                @Html.ValidationMessageFor(model => model.HomePhone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.CellNumber)
                @Html.ValidationMessageFor(model => model.CellNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarreerId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarreerId", String.Empty)
                @Html.ValidationMessageFor(model => model.CarreerId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

	 @Html.HiddenFor(model => model.CreationDate)
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionEn, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.DescriptionEn)
                @Html.ValidationMessageFor(model => model.DescriptionEn)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescriptionAr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                                  @Html.EditorFor(model => model.DescriptionAr)
                @Html.ValidationMessageFor(model => model.DescriptionAr)
            </div>
        </div>

        <div class="form-group" id="buttons">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-primary" />
				@Html.ActionLink("بازگشت به فهرست", "Index")
            </div>
        </div>
    </div>
}

MashadLeatherEcommerce/Views/CarreerIntroduceds/Index.cshtml
@model IEnumerable<Models.CarreerIntroduced>

@{
ViewBag.Title = "معرف";
    
    Layout = "~/Views/Shared/BackEndLayout/_BackEndLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

        @(Html.Kendo().Grid(Model)
              .Name("Grid")
              .Columns(columns =>
                  {
                                        columns.Bound(model => model.Carreer.FullName);
        columns.Bound(model => model.FullName);
        columns.Bound(model => model.Relationship);
        columns.Bound(model => model.Job);
        columns.Bound(model => model.WorkPlace);
        columns.Bound(model => model.HomePhone);
        columns.Bound(model => model.CellNumber);
        columns.Bound(model => model.Address);
        columns.Bound(model => model.IsActive);
        columns.Bound(model => model.CreationDate);
					columns.Bound(item => @item.Id).Title("دستورات").Filterable(false).Groupable(false)
							.Template(@<text>
									@Html.ActionLink("ویرایش", "Edit", new {id = @item.Id}, new {@class = "k-button"})
									@Html.ActionLink("حذف", "Delete", new {id = @item.Id}, new {@class = "k-button"})
									</text>).Width(200);  
		})
		.ToolBar(toolbar =>
					{				
						toolbar.Custom().Action("Create","CarreerIntroduceds").Text("افزودن");                          
					}
		)         
		.DataSource(dataSource => dataSource
									.Server()
							
									.Model(model => model.Id(item => item.Id))
					)              
	)